import json, re, os

with open("lib/l10n/app_zh.arb", "r", encoding="utf-8") as f:
    base_data = json.load(f)

base_keys = {k: v for k, v in base_data.items() if not k.startswith("@")}

# ----------------- 粤语（广州话） -----------------
yue_dict = {
    "appTitle": "自在東湖",
    "settings": "設置",
    "agentSettings": "Agent 設置",
    "appearanceSettings": "外觀設置",
    "notificationSettings": "通知設置",
    "language": "語言設置",
    "followSystem": "跟隨系統",
    "simplifiedChinese": "簡體中文",
    "english": "English",
    "traditionalChineseHK": "繁體中文（中國香港）",
    "traditionalChineseTW": "繁體中文",
    "japanese": "日文",
    "spanish": "西班牙文",
    "french": "法文",
    "portuguese": "葡萄牙文",
    "russian": "俄文",
    "cantonese": "粵語（廣州話）",
    "wuSuzhou": "吳語（蘇州話）",
    "xiangChangsha": "湘語（長沙話）",
    "jianghuaiHefei": "江淮官話（合肥話）",
    "ganNanchang": "贛語（南昌話）",
    "tabHome": "主頁",
    "tabTimetable": "課表",
    "tabHomework": "功課",
    "tabNotice": "通知",
    "tabFunctions": "功能",
    "cancel": "取消",
    "confirm": "確定",
    "loggingInWait": "登入緊，唔該等陣...",
    "profile": "個人中心",
    "helpFeedback": "幫助與反饋",
    "aboutApp": "關於",
    "login": "登入",
    "logout": "登出",
    "save": "儲存",
    "refresh": "重新整理",
    "delete": "刪除",
    "edit": "編輯",
    "search": "搜尋",
    "all": "全部",
    "loading": "載入緊...",
    "retry": "再試一次",
    "close": "關閉",
    "back": "返去",
    "networkError": "網絡出咗問題，請檢查下網絡",
    "noData": "暫時冇資料",
    "copySuccess": "複製搞掂",
    "saveSuccess": "儲存搞掂",
    "deleteSuccess": "刪除搞掂",
    "updateSuccess": "更新搞掂",
    "loadFailed": "載入失敗",
    "unknownError": "出咗啲未知錯誤",
    "clickToLogin": "輕觸登入，用多啲功能",
    "logoutConfirmTitle": "確定要登出？",
    "logoutConfirmContent": "登出之後會清除本地登入憑證，而且唔會再同伺服器同步資料。",
    "checkUpdate": "睇下有冇更新",
    "openSourceLicenses": "開源許可證",
    "sendEmail": "寄電郵",
    "developer": "開發者",
    "loginTitle": "登入",
    "loginSubtitle": "唔該登入帳號繼續使用。",
    "studentId": "學號",
    "studentIdHint": "唔該輸入學號",
    "password": "密碼",
    "passwordHint": "唔該輸入密碼",
    "loginButton": "即刻登入",
    "guestMode": "遊客模式",
    "guestModeNotice": "遊客模式只可以睇到公開功能，要登入先可以用晒全部校園服務。",
    "homework": "功課",
    "timetable": "課表",
    "library": "圖書館",
    "funcSunshine": "陽光服務",
    "funcQuestionnaire": "問卷調查",
    "funcLeave": "請假申請",
    "funcPaymentCode": "付款碼",
    "funcRecharge": "校園卡增值",
    "funcLibrary": "圖書館預約",
    "funcBus": "校車動態",
    "funcElectricity": "電費查詢及增值",
    "funcScore": "成績查詢",
    "funcClassroom": "吉教室查詢",
    "funcVpn": "WebVPN 轉換",
    "funcNotice": "教務通知",
    "funcTransaction": "校園卡流水",
    "reserveSeat": "約位",
    "signInSeat": "簽到",
    "signBackSeat": "退座",
    "cardBalance": "卡入面剩返",
    "todayClasses": "今日有咩堂",
    "noClassesToday": "今日冇堂，好好放鬆下啦！",
    "foundNewVersion": "睇到有新版本 v{version}",
    "updateNow": "即刻更新",
    "later": "等陣先",
}

# ----------------- 吴语（苏州话） -----------------
wuu_dict = {
    "appTitle": "自在东湖",
    "settings": "设定",
    "agentSettings": "Agent 调理",
    "appearanceSettings": "模样设定",
    "notificationSettings": "通告设定",
    "language": "说话设置",
    "followSystem": "随系统来",
    "simplifiedChinese": "简体中文",
    "english": "English",
    "traditionalChineseHK": "繁体中文（中国香港）",
    "traditionalChineseTW": "繁体中文",
    "japanese": "日语",
    "spanish": "西班牙语",
    "french": "法语",
    "portuguese": "葡萄牙语",
    "russian": "俄语",
    "cantonese": "粤语（广州话）",
    "wuSuzhou": "吴语（苏州话）",
    "xiangChangsha": "湘语（长沙话）",
    "jianghuaiHefei": "江淮官话（合肥话）",
    "ganNanchang": "赣语（南昌话）",
    "tabHome": "头一页",
    "tabTimetable": "课表",
    "tabHomework": "功课",
    "tabNotice": "通告",
    "tabFunctions": "用场",
    "cancel": "覅了",
    "confirm": "照办",
    "loggingInWait": "正在登进来，请耐心等歇...",
    "profile": "自家中心",
    "helpFeedback": "讨教与反馈",
    "aboutApp": "有关",
    "login": "登进来",
    "logout": "退出去",
    "save": "存落来",
    "refresh": "重新翻一趟",
    "delete": "汰脱",
    "edit": "改改",
    "search": "寻一寻",
    "all": "全数",
    "loading": "拿进来紧...",
    "retry": "重新再来一趟",
    "close": "关脱",
    "back": "转去",
    "networkError": "网络出脱毛病哉，去望望网络好口弗好",
    "noData": "啥物事都朆有",
    "copySuccess": "抄好哩",
    "saveSuccess": "存好哩",
    "deleteSuccess": "汰脱哩",
    "updateSuccess": "弄好新个哩",
    "loadFailed": "朆拿进来",
    "unknownError": "出脱弗识得个毛病哉",
    "clickToLogin": "捺一记登进来，好多物事好看",
    "logoutConfirmTitle": "阿是真个要退出去？",
    "logoutConfirmContent": "退出去之后本地凭证都汰脱哉，勿会再跟服务器同步物事哩。",
    "checkUpdate": "望望有新版本弗曾",
    "openSourceLicenses": "开源许可证",
    "sendEmail": "发封电邮",
    "developer": "做软件个人",
    "loginTitle": "登进来",
    "loginSubtitle": "请先登进来，好接着弄。",
    "studentId": "学号",
    "studentIdHint": "请输入学号",
    "password": "密码",
    "passwordHint": "请输入密码",
    "loginButton": "豪慅登进来",
    "guestMode": "闲逛模式",
    "guestModeNotice": "闲逛模式只能望望公开用场，登进来方能用全数校园服务。",
    "homework": "功课",
    "timetable": "课表",
    "library": "藏书楼",
    "funcSunshine": "阳光效劳",
    "funcQuestionnaire": "调查问卷",
    "funcLeave": "告假申请",
    "funcPaymentCode": "付钱码",
    "funcRecharge": "充铜钿",
    "funcLibrary": "藏书楼订位子",
    "funcBus": "校车走动",
    "funcElectricity": "查电费充铜钿",
    "funcScore": "考成分数",
    "funcClassroom": "闲教室查询",
    "funcVpn": "WebVPN 换换",
    "funcNotice": "教务通告",
    "funcTransaction": "校园卡账目",
    "reserveSeat": "订坐位",
    "signInSeat": "报到",
    "signBackSeat": "退坐位",
    "cardBalance": "卡里还有铜钿",
    "todayClasses": "今日子有啥课",
    "noClassesToday": "今日子朆有课，适意休息休息！",
    "foundNewVersion": "寻着新版本 v{version}",
    "updateNow": "豪慅更新",
    "later": "晏歇再讲",
}

# ----------------- 湘语（长沙话） -----------------
hsn_dict = {
    "appTitle": "自在东湖",
    "settings": "设置",
    "agentSettings": "Agent 调哈子",
    "appearanceSettings": "皮囊设置",
    "notificationSettings": "广播设置",
    "language": "话把子设置",
    "followSystem": "随系统走",
    "simplifiedChinese": "简体中文",
    "english": "English",
    "traditionalChineseHK": "繁体中文（中国香港）",
    "traditionalChineseTW": "繁体中文",
    "japanese": "日文",
    "spanish": "西班牙文",
    "french": "法文",
    "portuguese": "葡萄牙文",
    "russian": "俄文",
    "cantonese": "粤语（广州话）",
    "wuSuzhou": "吴语（苏州话）",
    "xiangChangsha": "湘语（长沙话）",
    "jianghuaiHefei": "江淮官话（合肥话）",
    "ganNanchang": "赣语（南昌话）",
    "tabHome": "首页",
    "tabTimetable": "课表",
    "tabHomework": "搞作业",
    "tabNotice": "通知",
    "tabFunctions": "百宝箱",
    "cancel": "算了啵",
    "confirm": "搞扎实",
    "loggingInWait": "正在登进来，莫急啵...",
    "profile": "个人屋里",
    "helpFeedback": "找指点与提意见",
    "aboutApp": "搞么子的",
    "login": "登进来",
    "logout": "退出来",
    "save": "记起",
    "refresh": "重新调哈",
    "delete": "甩脱",
    "edit": "改哈子",
    "search": "寻哈看",
    "all": "哈是",
    "loading": "莫慌，正在搞...",
    "retry": "再搞一回",
    "close": "关掉",
    "back": "回克",
    "networkError": "搞鬼哦，网扯拐哒，看哈网啵",
    "noData": "冇得么子看头",
    "copySuccess": "搞好哒，抄起哒",
    "saveSuccess": "存得扎实",
    "deleteSuccess": "甩脱哒",
    "updateSuccess": "搞成新个哒",
    "loadFailed": "冒搞出名堂",
    "unknownError": "见鬼哒，冒认得咯是么子问题",
    "clickToLogin": "戳一哈登进来，看蛮多功能",
    "logoutConfirmTitle": "真格要退出来啵？",
    "logoutConfirmContent": "退出来之后本地凭证哈莫得哒，而且再莫得跟服务器对齐数据哒。",
    "checkUpdate": "望哈有冒得新版",
    "openSourceLicenses": "开源讲究",
    "sendEmail": "扯封信克",
    "developer": "搞软件的伢子",
    "loginTitle": "登进来",
    "loginSubtitle": "莫急，登进来再搞。",
    "studentId": "学号",
    "studentIdHint": "把学号写进克",
    "password": "密码",
    "passwordHint": "把密码写进克",
    "loginButton": "赶忙登进来",
    "guestMode": "打流模式",
    "guestModeNotice": "打流模式只能瞄哈公开的，登进来才搞得成全部校园服务。",
    "homework": "搞作业",
    "timetable": "课表",
    "library": "图书楼",
    "funcSunshine": "阳光跑腿",
    "funcQuestionnaire": "填问卷",
    "funcLeave": "告假申请",
    "funcPaymentCode": "付账码",
    "funcRecharge": "充饭卡",
    "funcLibrary": "占座位",
    "funcBus": "校车跑哪哒",
    "funcElectricity": "查电费塞钱",
    "funcScore": "看哈分数",
    "funcClassroom": "闲教室在哪",
    "funcVpn": "WebVPN 换哈子",
    "funcNotice": "教务广播",
    "funcTransaction": "饭卡流水账",
    "reserveSeat": "占位子",
    "signInSeat": "踩点签到",
    "signBackSeat": "退位子溜号",
    "cardBalance": "卡里还有几文钱",
    "todayClasses": "今日有么子堂",
    "noClassesToday": "今日冒得堂，好生玩哈子！",
    "foundNewVersion": "看到有新版本 v{version}",
    "updateNow": "赶紧搞好",
    "later": "随后再扯",
}

# ----------------- 江淮官话（合肥话） -----------------
hefei_dict = {
    "appTitle": "自在东湖",
    "settings": "设置",
    "agentSettings": "Agent 设置",
    "appearanceSettings": "外观设置",
    "notificationSettings": "通知设置",
    "language": "语言设置",
    "followSystem": "跟随系统",
    "simplifiedChinese": "简体中文",
    "english": "English",
    "traditionalChineseHK": "繁体中文（中国香港）",
    "traditionalChineseTW": "繁体中文",
    "japanese": "日语",
    "spanish": "西班牙语",
    "french": "法语",
    "portuguese": "葡萄牙语",
    "russian": "俄语",
    "cantonese": "粤语（广州话）",
    "wuSuzhou": "吴语（苏州话）",
    "xiangChangsha": "湘语（长沙话）",
    "jianghuaiHefei": "江淮官话（合肥话）",
    "ganNanchang": "赣语（南昌话）",
    "tabHome": "首页",
    "tabTimetable": "课表",
    "tabHomework": "作业",
    "tabNotice": "通知",
    "tabFunctions": "功能",
    "cancel": "取消",
    "confirm": "确定",
    "loggingInWait": "正在登录，请稍候...",
    "profile": "个人中心",
    "helpFeedback": "帮助与反馈",
    "about": "关于",
    "aboutApp": "关于",
    "login": "登录",
    "logout": "退出登录",
    "save": "保存",
    "refresh": "刷新",
    "delete": "删除",
    "edit": "编辑",
    "search": "搜索",
    "all": "全部",
    "loading": "加载中...",
    "retry": "重试",
    "close": "关闭",
    "back": "返回",
    "networkError": "网络连接失败，请检查网络",
    "noData": "没得数据",
    "loadFailed": "加载失败",
    "clickToLogin": "点击登录以访问更多功能",
    "logoutConfirmTitle": "确认退出",
    "logoutConfirmContent": "退出登录后将清除您的本地凭证并断开数据连接。",
    "checkUpdate": "检查更新",
    "openSourceLicenses": "开源声明",
    "sendEmail": "发送邮件",
    "developer": "开发者",
    "loginTitle": "登录",
    "loginSubtitle": "请登录以继续。",
    "studentId": "学号",
    "studentIdHint": "请输入学号",
    "password": "密码",
    "passwordHint": "请输入密码",
    "loginButton": "登录",
    "funcSunshine": "阳光服务",
    "funcQuestionnaire": "学工问卷",
    "funcLeave": "请假申请",
    "funcPaymentCode": "付款码",
    "funcRecharge": "校园卡充值",
    "funcLibrary": "图书馆",
    "funcBus": "实时校车",
    "funcScore": "成绩查询",
    "funcVpn": "VPN转换",
    "reserveSeat": "预约选座",
    "foundNewVersion": "发现新版本 v{version}",
    "updateNow": "立即更新",
    "later": "以后再说",
    "loginRequiredTitle": "需要登录以查看内容",
    "loginRequiredMessage": "登录后即可查看您的课表、作业和成绩信息",
    "openSystemSettingsFailed": "打不开系统设置，请手动去设置 > 通知里查看",
    "timetableLoginRequiredTitle": "需要登录以查看课表",
    "timetableLoginRequiredMessage": "登录后即可同步并查看您的个人课表信息",
    "viewAll": "查看全部",
    "viewAction": "查看",
    "newVersionFoundSnackBar": "🚀 发现新版本 v{version}，点击查看详情",
    "loggingInPleaseWait": "正在登录，请稍候...",
    "paymentProcessingWechatHint": "支付处理中，请在微信中完成支付后稍候查询",
    "paymentProcessingAlipayHint": "暂未查询到到账，请在支付宝中完成支付后稍候重试",
    "pleaseWaitDoNotClose": "请稍候，请勿关闭页面",
    "paymentNotice": "付款提示",
    "appealSubmitPhoneCodeInvalidMsg": "平台提示手机号或验证码不正确。请核对手机号；如需验证码，请在阳光服务官网完成验证。"
}

def generate_dialect_arb(locale_tag, specific_dict, tone_replacements, out_path):
    out = {"@@locale": locale_tag}
    for k, v in base_keys.items():
        if k in specific_dict:
            res = specific_dict[k]
        else:
            res = v
            # Apply common tone replacements
            for old, new in tone_replacements.items():
                # Avoid touching placeholders!
                parts = re.split(r"(\{[a-zA-Z0-9_]+\})", res)
                new_parts = []
                for p in parts:
                    if p.startswith("{") and p.endswith("}"):
                        new_parts.append(p)
                    else:
                        new_parts.append(p.replace(old, new))
                res = "".join(new_parts)
        out[k] = res
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"Generated {out_path}")

# Common rules for yue
import opencc
cc_hk = opencc.OpenCC("s2hk")
yue_replacements = {
    "正在": "喺度",
    "没有": "冇",
    "不": "唔",
    "如果": "如果話",
    "可以": "可以",
    "请": "唔該",
    "你的": "你嘅",
    "我的": "我嘅",
    "查看": "睇吓",
    "设置": "設置",
}

# Generate yue by starting from cc_hk converted text + yue dict
out_yue = {"@@locale": "yue"}
for k, v in base_keys.items():
    if k in yue_dict:
        out_yue[k] = yue_dict[k]
    else:
        parts = re.split(r"(\{[a-zA-Z0-9_]+\})", v)
        converted_parts = []
        for p in parts:
            if p.startswith("{") and p.endswith("}"):
                converted_parts.append(p)
            else:
                conv = cc_hk.convert(p)
                conv = conv.replace("設置", "設置").replace("登錄", "登入").replace("默認", "預設")
                conv = conv.replace("正在", "緊").replace("請問", "唔該問下").replace("請", "唔該")
                converted_parts.append(conv)
        out_yue[k] = "".join(converted_parts)

with open("lib/l10n/app_yue.arb", "w", encoding="utf-8") as f:
    json.dump(out_yue, f, ensure_ascii=False, indent=2)
print("Generated lib/l10n/app_yue.arb")

# Generate wuu
wuu_replacements = {
    "的": "个",
    "了吗": "哉弗曾",
    "了吗？": "哉弗曾？",
    "没有": "朆有",
    "不要": "覅",
    "请稍候": "请耐歇等歇",
    "稍候": "等歇",
    "马上": "豪慅",
    "查看": "望望",
    "提示": "通告",
}
generate_dialect_arb("wuu", wuu_dict, wuu_replacements, "lib/l10n/app_wuu.arb")

# Generate hsn
hsn_replacements = {
    "了吗": "哒冒咯",
    "了吗？": "哒冒咯？",
    "没有": "冇得",
    "不要": "莫搞",
    "请稍候": "莫急啵，等下子",
    "稍候": "等下子",
    "马上": "赶紧",
    "查看": "瞄哈看",
    "提示": "提醒哈",
    "确定要": "真格要",
}
generate_dialect_arb("hsn", hsn_dict, hsn_replacements, "lib/l10n/app_hsn.arb")

# Generate zh_hefei
hefei_replacements = {
    "没有": "没得",
}
generate_dialect_arb("zh_hefei", hefei_dict, hefei_replacements, "lib/l10n/app_zh_hefei.arb")

print("All 4 dialects generated!")
